/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'clouway' at '8/16/16 2:51 PM' with Gradle 2.10
 *
 * @author clouway, @date 8/16/16 2:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
